// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b14c048c-4737-44f0-a853-c2cde770ce5e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_fLWpurrZC",
    "aws_user_pools_web_client_id": "l2se764kehhb9r5ub03n8b48t",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://yddotpgew5hxxa7jxayc6hvrai.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
